# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pynotebooks',
                'doc_host': 'https://BrunodsLilly.github.io',
                'git_url': 'https://github.com/BrunodsLilly/pynotebooks',
                'lib_path': 'pynotebooks'},
  'syms': {'pynotebooks.core': {'pynotebooks.core.foo': ('core.html#foo', 'pynotebooks/core.py')}}}
