"""Implements simple linear regression following Andrew Ng's ML course"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/linear_regression.ipynb.

# %% auto 0
__all__ = ['cost', 'SimpleLinearRegressor']

# %% ../nbs/linear_regression.ipynb 4
def cost(y: jnp.ndarray, f: Callable[..., jnp.ndarray], *params: Any) -> float:
    """Compute the cost function for linear regression.
    
    Parameters
    ----------
    y : ndarray of shape (m,)
        Target values for the training examples.
    f : callable
        Prediction function that takes parameters and returns predictions.
    *params
        Variable length argument list of parameters to be passed to the 
        prediction function f.
    
    Returns
    -------
    float
        The mean squared error cost of using the given parameters for 
        linear regression to fit the data points.
    """
    m = len(y)  # the number of training examples
    errors = f(*params) - y
    
    # return the sum of squared errors
    return 1/(2*m) * jnp.dot(errors, errors)

# %% ../nbs/linear_regression.ipynb 6
class SimpleLinearRegressor:
    """A simple linear regressor."""

    def predict():
        """Runs regression on inputs and returns an output."""
        ...
